config/routes.rb
NateMcgarigal::Application.routes.draw do
  root :to => 'application#index'
  
  resources :photo_galleries
  resources :photos
  resources :tags
    
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post  
end

app/models/photo_gallery.rb
class PhotoGallery < ActiveRecord::Base
  attr_accessible :name, :tag_ids
  
  has_many :photo_gallery_taggings
  has_many :tags, :through => :photo_gallery_taggings
  
end

app/controllers/photo_galleries_controller.rb
class PhotoGalleriesController < ApplicationController
  # GET /photo_galleries
  # GET /photo_galleries.json
  def index
    @photo_galleries = PhotoGallery.all

    @photos = Array.new

    respond_to do |format|
      format.html # index.html.erb
      format.json {  @photo_galleries }
    end
  end

  # GET /photo_galleries/1
  # GET /photo_galleries/1.json
  def show
    @photo_gallery = PhotoGallery.find(params[:id])
    
    @photos = Array.new
    @photos_json = Array.new
    
    @photo_gallery.tags.each do |tag|
      tag.photos.each do |photo|
        photo[:path_small] = photo.image.url(:small)
        photo[:path_medium] = photo.image.url(:medium)
        photo[:path_large] = photo.image.url(:large)
        @photos.push(photo);
      end
    end
    
    @photos = @photos.flatten
    
    @gallery = {
      :id => @photo_gallery.id,
      :name => @photo_gallery.name,
      :photos => @photos
    }
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { @gallery }
    end
  end

  # GET /photo_galleries/new
  # GET /photo_galleries/new.json
  def new
    @photo_gallery = PhotoGallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo_gallery }
    end
  end

  # GET /photo_galleries/1/edit
  def edit
    @photo_gallery = PhotoGallery.find(params[:id])
  end

  # POST /photo_galleries
  # POST /photo_galleries.json
  def create
    @photo_gallery = PhotoGallery.new(params[:photo_gallery])

    respond_to do |format|
      if @photo_gallery.save
        format.html { redirect_to @photo_gallery, notice: 'Photo gallery was successfully created.' }
        format.json { render json: @photo_gallery, status: :created, location: @photo_gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @photo_gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photo_galleries/1
  # PUT /photo_galleries/1.json
  def update
    @photo_gallery = PhotoGallery.find(params[:id])

    respond_to do |format|
      if @photo_gallery.update_attributes(params[:photo_gallery])
        format.html { redirect_to @photo_gallery, notice: 'Photo gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo_gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photo_galleries/1
  # DELETE /photo_galleries/1.json
  def destroy
    @photo_gallery = PhotoGallery.find(params[:id])
    @photo_gallery.destroy

    respond_to do |format|
      format.html { redirect_to photo_galleries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/photo_galleries_helper.rb
module PhotoGalleriesHelper
end

app/views/photo_galleries/_form.html.erb
<%= form_for(@photo_gallery) do |f| %>
  <% if @photo_gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo_gallery.errors.count, "error") %> prohibited this photo_gallery from being saved:</h2>

      <ul>
      <% @photo_gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
   <div class='field'>
    <%= hidden_field_tag "photo_gallery[tag_ids][]", nil %>
    <% Tag.all.each do |tag| %>
      <%=check_box_tag "photo_gallery[tag_ids][]", tag.id, @photo_gallery.tag_ids.include?(tag.id) %>
      <%= tag.name %><br />
    <% end %>
  </div>
  
  <div class='field'>
    <%= check_box_tag "photo_gallery[public]", @photo_gallery.public, @photo_gallery.public %>
    Public    
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photo_galleries/edit.html.erb
<h1>Editing photo_gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo_gallery %> |
<%= link_to 'Back', photo_galleries_path %>

app/views/photo_galleries/index.html.erb
<h1>Listing photo_galleries</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photo_galleries.each do |photo_gallery| %>
  <tr>
    <td><%= link_to photo_gallery.name, photo_gallery %></td>
    <td><%= link_to 'Edit', edit_photo_gallery_path(photo_gallery) %></td>
    <td><%= link_to 'Destroy', photo_gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo gallery', new_photo_gallery_path %>

app/views/photo_galleries/new.html.erb
<h1>New photo_gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', photo_galleries_path %>

app/views/photo_galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @photo_gallery.name %>
</p>

<p>
  <% @photos.each do |photo| %>
    <%= image_tag photo.image.url(:large) %>
  <% end %>
</p>

<%= link_to 'Edit', edit_photo_gallery_path(@photo_gallery) %> |
<%= link_to 'Back', photo_galleries_path %>